# SGC-FileCopyrightText: 2026 - 2026 Oneill
#
# SGC-License-Identifier: AGPL-3.0-or-later
---

# This needs to always run, because it populates `playbook_uid` and `playbook_gid`,
# which are required by many other roles.
- block:
    - ansible.builtin.include_tasks: "{{ role_path }}/tasks/setup_user.yml"
  tags:
    - always
    - setup-system-user

- block:
    - ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - ansible.builtin.include_tasks: "{{ role_path }}/tasks/setup_base_dir.yml"
  tags:
    - setup-all
    - install-all
