# SGC-FileCopyrightText: 2026 - 2026 Oneill
#
# SGC-License-Identifier: AGPL-3.0-or-later
---

- name: Ensure base paths exists
  ansible.builtin.file:
    path: "{{ sgc_playbook_base_path }}"
    state: directory
    mode: "{{ sgc_playbook_base_path_mode }}"
    owner: "{{ sgc_playbook_uid }}"
    group: "{{ sgc_playbook_gid }}"
