#  2026 - 2026 Oneill
#
#  AGPL-3.0-or-later

---

- name: Fail if required playbook settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item.name }}`).
  when: "item.when | bool and lookup('vars', item.name, default='') | string | length == 0"
  with_items:
    - {'name': 'sgc_pgsk', 'when': true}
    - {'name': 'sgc_pgsk', 'when': true}
    - {'name': 'expose_metrics_hostname', 'when': "{{ expose_metrics_hostname_enabled }}"}

- name: Fail if playbook_reverse_proxy_type is set incorrectly
  ansible.builtin.fail:
    msg: "Detected that variable rev_proxy_type (current value: `{{ rev_proxy_type }}`) appears to be set incorrectly. See roles/custom/mash_playbook_base/defaults/main.yml for valid choices."
  when: rev_proxy_type not in ['playbook-managed-traefik', 'other-traefik-container', 'none']

- name: (Deprecation) Catch and report renamed mash-playbook settings
  ansible.builtin.fail:
    msg: >-
      Your configuration contains a variable, which now has a different name.
      Please rename the variable (`{{ item.old }}` -> `{{ item.new }}`) on your configuration file (vars.yml).
  when: "lookup('ansible.builtin.varnames', ('^' + item.old + '$'), wantlist=True) | length > 0"
  with_items:
    - {'old': 'mash_playbook_user_username', 'new': 'sgc_playbook_user'}
    - {'old': 'mash_playbook_user_groupname', 'new': 'sgc_playbook_group_name'}
